# Generated by Django 4.2.7 on 2024-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogmodel_title_alter_blogmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
