# Generated by Django 4.2.7 on 2024-01-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_title_alter_blogmodel_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
    ]
