# Generated by Django 4.2.7 on 2024-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blogmodel_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
    ]
