# Generated by Django 4.2.7 on 2024-01-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='title', max_length=100)),
                ('email', models.CharField(default='author', max_length=100)),
                ('your_message', models.CharField(default='description', max_length=2000)),
            ],
        ),
    ]
