# Generated by Django 4.2.7 on 2024-01-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='your_message',
            field=models.CharField(default='your_message', max_length=2000),
        ),
    ]
